feat(*): autoopen taskpane with document feature
accordproject/cicero-word-add-in-deprecated pull request #135
Opened 2020-04-25 20:12 UTC by arteevraina

## Fixes: #133 

## Screenshot
![image](https://user-images.githubusercontent.com/43968121/80289818-e4970700-875e-11ea-86b7-74c99fd347bd.png)

`AutoOpen` Feature now works perfectly fine with `Checkbox`. Please Review and suggest changes @DianaLease @Michael-Grover @dselman :) 

Signed-off-by: Arteev Raina <arteevraina@gmail.com>

2020-04-27 13:13 UTC, DianaLease approved these changes
nice!

2020-04-27 13:32 UTC, DianaLease requested changes
Updating review, discussed issue via Slack

2020-04-27 13:43 UTC, Michael-Grover commented
My comment would be to make it look like the mockup I shared [here](https://github.com/accordproject/cicero-word-add-in/pull/134)

> I don't think a side drawer is necessary yet as we only have one setting.
> 
> For now let's put it here and if there are more settings in the future, we can consider a dedicated page or side drawer for them.
> ![image](https://user-images.githubusercontent.com/40569793/80378764-2614d880-886b-11ea-9341-95eed8e47ef4.png)

However I still think we should consider shelving this feature. I looked at many Word add-ins on Friday to get a better understanding of common practices, and I didn't notice an auto-open feature in any of them.

2020-04-27 14:13 UTC, arteevraina commented
Hi @Michael-Grover :) I think this feature would be useful for lawyers who would be using this Accord Project templates in word document and we don't  want them to everytime they open the document to explicitly open the `taskpane` which would be pretty time consuming for `laywers` who frequently open the document in word. Also, through this feature we can create a base for developing another feature for prompting the user for installing the add-in if not already installed if he opens a document that uses AP templates.

2020-04-27 17:00 UTC, arteevraina commented
![image](https://user-images.githubusercontent.com/43968121/80399258-8c831080-88d6-11ea-8f62-1de760300ed4.png)

@Michael-Grover Changed the add-in to look like the one in the mockup and fixed the earlier issue discussed with @DianaLease on Slack :)

2020-04-28 18:19 UTC, DianaLease approved these changes
LGTM!

2020-04-28 18:20 UTC, merged