fix(smart clause dialog): remove state persistence
accordproject/cicero-word-add-in-deprecated pull request #38
Opened 2020-03-17 19:56 UTC by shakti97

Signed-off-by: shakti97 <shaktisingh230797@gmail.com>

Fixes #37

2020-03-17 22:33 UTC, DianaLease requested changes

2020-03-17 22:33 UTC, DianaLease commented on src/NewSmartClauseDialog.js
> +    this.setState({ open: false,clauseId: '', templateId: '' });
super small change, but can you add a space before `clauseId` please ?

2020-03-18 04:54 UTC, shakti97 commented on src/NewSmartClauseDialog.js
> +    this.setState({ open: false,clauseId: '', templateId: '' });
Done

2020-03-18 18:54 UTC, shakti97 commented
@DianaLease can you please review and suggest changes if any

2020-03-18 19:09 UTC, DianaLease approved these changes

2020-03-18 19:09 UTC, merged