add react hot loader to improve the performance in a running addin during coding
accordproject/cicero-word-add-in-deprecated pull request #42
Opened 2020-03-18 08:13 UTC by ShrutikaSingh

React Hot Loader is used to edit our code and automatically reflect that change in our running addin while keeping the components mounted, without lose the current state. It's pretty convenient as we won't have to go step-by-step to test a specific state in our app every time we make a change in the code.

2020-03-18 18:06 UTC, DianaLease requested changes
Nice! Can you just change the class components I commented on to functional components please?

2020-03-18 18:06 UTC, DianaLease commented on src/App.js
> +class App extends Component {
Why was this changed back to a class component? We should aim to always use functional components.

2020-03-18 18:06 UTC, DianaLease commented on src/Progress.js
> +class Progress extends Component {
This can also be a functional component.

2020-03-18 18:56 UTC, nik72619c requested changes

2020-03-18 18:56 UTC, nik72619c commented on package.json
> +    "react-spinner-material": "^1.2.0",
@ShrutikaSingh Material-UI has a wide range of spinners already, and this package is present in the project. I don't think its wise to add a separate package for this and increase the bundle size unnecessarily. @DianaLease would love to hear your thoughts on this.

2020-03-18 18:59 UTC, ShrutikaSingh commented on package.json
> +    "react-spinner-material": "^1.2.0",
Like in future its discussed that we need to refactor the code to style components, so keeping that in mind, I plugged the spinner from npm itself, @DianaLease, what are your views about this, like keep this one or import one from material ui

2020-03-18 19:25 UTC, ShrutikaSingh commented
@DianaLease Updated with the changes suggested, please review.

2020-03-18 20:23 UTC, ShrutikaSingh commented on src/App.js
> +class App extends Component {
@DianaLease Sure

2020-03-18 20:41 UTC, ShrutikaSingh commented
@DianaLease Updated the directory structure so that it will be inconsistency with cicero-UI

2020-03-18 23:02 UTC, DianaLease commented on package.json
> +    "react-spinner-material": "^1.2.0",
Let's use the material ui one. Thanks!

2020-03-19 05:34 UTC, ShrutikaSingh commented on package.json
> +    "react-spinner-material": "^1.2.0",
Sure!!

2020-03-19 06:04 UTC, ShrutikaSingh commented on package.json
> +    "react-spinner-material": "^1.2.0",
> Let's use the material ui one. Thanks!

@DianaLease Done. Thanks

2020-03-20 07:11 UTC, ShrutikaSingh commented
@DianaLease Do anything else need to be changed?

2020-03-20 14:20 UTC, DianaLease requested changes
Looks good once conflicts are resolved!

2020-03-20 14:20 UTC, DianaLease commented on src/Navigation/TopNavigation.js
> +>>>>>>> 1ede732a2d34ac189a733b8867ec2d0adda1a08d:src/TopNavigation.js
conflicts here should be resolved

2020-03-20 14:27 UTC, ShrutikaSingh commented on src/Navigation/TopNavigation.js
> +>>>>>>> 1ede732a2d34ac189a733b8867ec2d0adda1a08d:src/TopNavigation.js
@DianaLease Done, thanks:)

2020-03-20 15:02 UTC, DianaLease commented
@ShrutikaSingh thanks! can you also resolve the new conflicts that need to be resolved before merging?

2020-03-20 21:23 UTC, ShrutikaSingh commented
> @ShrutikaSingh thanks! can you also resolve the new conflicts that need to be resolved before merging?

yup!! done

2020-03-20 21:24 UTC, DianaLease requested changes

2020-03-20 21:24 UTC, DianaLease commented on src/ClauseEditor/NewSmartClauseDialog.js
> +>>>>>>> c8878f43d3ecd87dcd7e800b837cb29c3c52ecad:src/NewSmartClauseDialog.js
still some unresolved conflicts here

2020-03-20 21:24 UTC, DianaLease commented on src/Navigation/TopNavigation.js
> +>>>>>>> c8878f43d3ecd87dcd7e800b837cb29c3c52ecad:src/TopNavigation.js
here too

2020-03-20 22:34 UTC, ShrutikaSingh commented on src/ClauseEditor/NewSmartClauseDialog.js
> +>>>>>>> c8878f43d3ecd87dcd7e800b837cb29c3c52ecad:src/NewSmartClauseDialog.js
Actually I resolve the commit, and then you push changes of another pull request so may be it shows conflicts again because other people are using codes before my pull request is merged, I am resolving these conflicts again, so can you push my code first and then after theirs, cause I have put many files in components structure so its giving conflict with other prs since they are still using the previous codes.

2020-03-20 22:36 UTC, ShrutikaSingh commented on src/Navigation/TopNavigation.js
> +>>>>>>> c8878f43d3ecd87dcd7e800b837cb29c3c52ecad:src/TopNavigation.js
Same here, I have used the react component like directory structure, and since you merge another pr first, its giving this issue, can you please merge this pr first.

2020-03-22 00:21 UTC, DianaLease approved these changes

2020-03-22 00:21 UTC, merged