refactor(*): removed console log statements
accordproject/cicero-word-add-in-deprecated pull request #48
Opened 2020-03-18 20:16 UTC by nik72619c

Fixes #47 
@DianaLease @dselman

2020-03-18 20:56 UTC, shakti97 requested changes

2020-03-18 20:56 UTC, shakti97 commented on src/TemplateList.js
> -        console.log("Error: " + error);
removing logging error I don't think its a nice idea for now or if you really want it to do so you should handle it properly like showing any user friendly message

2020-03-18 21:01 UTC, nik72619c commented on src/TemplateList.js
> -        console.log("Error: " + error);
@shakti97 , I agree. At least this error could help in identifying such errors. @DianaLease @dselman should revert this console.log statement ?

2020-03-18 23:00 UTC, DianaLease commented on src/TemplateList.js
> -        console.log("Error: " + error);
Yes, I think we should keep that until we have a proper way of surfacing errors in the UI. Also, you could use `console.error` instead of `console.log` here.

2020-03-20 19:55 UTC, nik72619c commented
@DianaLease made the required changes :)

2020-03-20 19:56 UTC, DianaLease approved these changes

2020-03-20 19:56 UTC, merged