feat(add to contract): fix contract does not add to the current curso…
accordproject/cicero-word-add-in-deprecated pull request #93
Opened 2020-03-22 19:09 UTC by nik72619c

Fixes #92 

Signed-off-by: nik72619c <nikhilsharmarockstar21@gmail.com>

@DianaLease @dselman please review it and let me know of any changes.

2020-03-23 19:48 UTC, DianaLease requested changes

2020-03-23 19:48 UTC, DianaLease commented on src/TemplateEditor/TemplateList.js
> +        context.document.getSelection().insertHtml(html, 'End');
This is great, but can we instead do
```
context.document.getSelection().insertParagraph('', 'After').insertHtml(html, 'End');
```
so that the clause starts in a new paragraph?

2020-03-29 19:13 UTC, DianaLease commented on src/TemplateEditor/TemplateList.js
> +        context.document.getSelection().insertHtml(html, 'End');
@nik72619c Following up on the comment above ^

2020-04-02 17:29 UTC, nik72619c commented on src/TemplateEditor/TemplateList.js
> +        context.document.getSelection().insertHtml(html, 'End');
got it, making the required changes !

2020-04-02 17:32 UTC, nik72619c commented on src/TemplateEditor/TemplateList.js
> +        context.document.getSelection().insertHtml(html, 'End');
@DianaLease made the requested changes :)

2020-04-09 18:50 UTC, DianaLease approved these changes

2020-04-09 18:50 UTC, merged